# Generated by Django 5.1.1 on 2025-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('mobile', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'UserCredential',
                'verbose_name_plural': 'UserCredentials',
            },
        ),
    ]
