# Generated by Django 5.1.1 on 2025-04-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredentials',
            old_name='mobile',
            new_name='userid',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('user_type', models.CharField(choices=[('Customer', 'Customer'), ('Chef', 'Chef')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user_credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usercredentials')),
            ],
        ),
    ]
