# Generated by Django 5.1.1 on 2025-04-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_rename_mobile_usercredentials_userid_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Items',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=255)),
                ('food_type', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Food_Item',
                'verbose_name_plural': 'Food_Items',
            },
        ),
        migrations.CreateModel(
            name='Chef_Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food_items')),
            ],
            options={
                'verbose_name': 'Chef_Role',
                'verbose_name_plural': 'Chef_Roles',
            },
        ),
    ]
